Start of the search fragment
nOmeep/vk-education-android pull request #4
Opened 2022-03-19 21:57 UTC by nOmeep

Хочу узнать насколько норм или не нормнаписал это. А дальше уже продолжу если все ок. Сделал вьюпейджер, который подвязал к таблейауту, переключающемуся между двумя фрагментами(один для найденных фильмов, а другой для найденных людей). Хотел бы также узнать как стоит переделать костыль на 32 строке SearchFragment)

2022-03-19 22:02 UTC, nOmeep commented on app/src/main/java/com/example/viewed/ui/fragments/search/SearchAdapter.kt
> +}
Первый костыль, от которого бы хотелось избавиться, но пока не придумал как

2022-03-19 22:02 UTC, nOmeep commented on app/src/main/java/com/example/viewed/ui/fragments/search/SearchFragment.kt
> +            tab.text = if (position == 0) "Films" else "Actors"
а вот и второй костыль

2022-03-21 12:18 UTC, grigorevmp requested changes

2022-03-21 12:18 UTC, grigorevmp commented on app/src/main/res/layout/fragment_search.xml
> -            android:layout_margin="4dp"
Давай все константные значения в dimens. Дальше много хардкода такого. В AS можно быстро это делать: выделить -> show context actions -> "extract dimention resource"

2022-03-21 12:18 UTC, grigorevmp commented on app/src/main/res/layout/item_search_result_movie.xml
> +        android:layout_height="150dp">
А точно стоит фиксированную высоту делать? Почему wrap_content не подходит тут?

2022-03-21 12:18 UTC, grigorevmp commented on app/src/main/java/com/example/viewed/ui/fragments/search/SearchAdapter.kt
> +}
Ну мб только если через when красиво сделать

```
override fun createFragment(position: Int): Fragment {
        return when (position) {
            0 -> Fragment1()
            1 -> Fragment2()
            else -> BaseFragment()
        }
    }
```

2022-03-21 12:18 UTC, grigorevmp commented on app/src/main/java/com/example/viewed/ui/fragments/search/SearchFragment.kt
> +            tab.text = if (position == 0) "Films" else "Actors"
Тоже самое, смотри в сторону 'when', хотя бы для читаемости

2022-03-30 11:54 UTC, grigorevmp approved these changes

2022-04-11 10:42 UTC, nOmeep commented
Решил пока запушить пейджинг со старым апи, потом поменяем, тут вроде все ок должно быть

2022-04-11 14:21 UTC, grigorevmp approved these changes

2022-04-13 15:28 UTC, merged