Feature sashanau saved cards
nOmeep/vk-education-android pull request #6
Opened 2022-04-18 11:51 UTC by sashanau

Первая версия, не судите строго)

2022-04-18 12:01 UTC, grigorevmp requested changes

2022-04-18 12:01 UTC, grigorevmp commented on app/local.properties
> +sdk.dir=C\:\\Android\\SDK
Постарайся local.properties в гит игнор кинуть, а то у всех разный ж путь к сдк

2022-04-18 12:01 UTC, grigorevmp commented on app/src/main/java/com/example/viewed/ui/fragments/profile/ProfileFragment.kt
> +        }
Это блокирование главного потока? о_0
А можно не надо

2022-04-18 12:01 UTC, grigorevmp commented on app/src/main/java/com/example/viewed/ui/fragments/profile/ProfileFragment.kt
> +            }
Аналогично -_-

2022-04-18 12:01 UTC, grigorevmp commented on app/src/main/java/com/example/viewed/ui/fragments/profile/ProfileFragment.kt
> +            }
Аналогично -_-

2022-04-18 12:01 UTC, grigorevmp commented on app/src/main/java/com/example/viewed/ui/fragments/profile/ProfileFragment.kt
> +            }
Аналогично -_-

2022-04-19 12:05 UTC, nOmeep commented on app/src/main/java/com/example/viewed/db/CardsItems.kt
> +    @Insert(entity = CardsLater::class, onConflict = OnConflictStrategy.REPLACE)
почему вставка в бд не suspend функция?

2022-04-19 12:05 UTC, nOmeep commented on app/src/main/java/com/example/viewed/db/CardsItems.kt
> +    fun addCardWatch(card: CardsWatch)
аналогично сделать суспенд

2022-04-19 12:06 UTC, nOmeep commented on app/src/main/java/com/example/viewed/db/CardsItems.kt
> +    fun deleteCardViewed(id: Int)
удаления тоже бы суспендами сделать, если что недолгое будет, можно будет пофиксить потом

2022-04-19 12:08 UTC, nOmeep commented on app/src/main/java/com/example/viewed/db/items/CardsTables.kt
> +
все норм, но уже так и вижу баг, когда юзер сначала нажал плюс в одну категорию, потом плюс в другую, из-за чего у него один фильм в двух состояниях. Фильм шредингера?

2022-04-19 12:10 UTC, nOmeep commented on app/src/main/java/com/example/viewed/db/items/CardsTables.kt
> +    val Id: Int
почему все энтити только id имеют в качетве поля? Разве суть бд не в том чтобы закэшировать полностью данные о фильмах юзера? Пусть хранится полностью инфа о фильме (сделай поле типа Фильм, который в страничке подается, либо у Димы в классе)

2022-04-19 12:11 UTC, nOmeep commented on app/src/main/java/com/example/viewed/di/DBModule.kt
> +            .allowMainThreadQueries()
так нельзя делать, ай ай ай, выше написал что надо суспенд функции сделать и параллельно выполнять задачи. А это как костыль какой-то

2022-04-19 12:11 UTC, nOmeep commented on app/src/main/java/com/example/viewed/ui/fragments/profile/ProfileFragment.kt
> +class ProfileFragment : Fragment(R.layout.fragment_profile) {
спецом же сделал BaseFragment чтобы не было дублировния байндингов и onViewDestroyed во фрагментах

2022-04-19 12:16 UTC, nOmeep commented on app/src/main/java/com/example/viewed/ui/fragments/viewmodels/ProfileViewModel.kt
> +    }
почему во вьюмодели суспенд функции, которые к тому же ты во фрагменте потом и блокируешь, так что толку от них нет. Вообще можешь объяснить смысл такой вьюмодели? Тут лайвдата нужна, которую во фрагменте будут обсервить.

2022-04-19 12:18 UTC, nOmeep commented on app/src/main/java/com/example/viewed/ui/fragments/profile/ProfileItemsAdapter.kt
> +        @SuppressLint("NotifyDataSetChanged")
вот так делать имхо не стоит. У тебя вообще этого warning не должно возникать если все правильно сделано. Напиши через лайвдату во вьюмодели, которую observe во фрагменте и все ок будет. Для реактивности еще флоу в DAO добавить можно, но там пока просто ливдату надо

2022-04-19 12:21 UTC, nOmeep commented on app/src/main/java/com/example/viewed/ui/fragments/profile/ProfileItemsAdapter.kt
> +class ProfileItemsAdapter(
У этого класса не написан диффер, из-за чего все как-то костыльно выглядит с этими notifyDataSetChanged (мое имхо). Но не мое "имхо" это то, что тут очень дергано происходят изменения, нет плавности. Он каждый раз при получении новых данных удаляет старое и ждет пока появятся новые, а потом резко на пользователя вываливает это. Разве всегда нужно прям все удалять? Обычно нужно изменить часть только, либо вообще не трогать. Такую задачу и помогает решить диффер

2022-04-20 15:53 UTC, nOmeep commented on app/src/main/java/com/example/viewed/di/DBModule.kt
> +            .allowMainThreadQueries()
убрать

2022-04-20 15:54 UTC, nOmeep requested changes
Мейн тред для бд убрать, сменить название ДАО

2022-04-20 16:07 UTC, nOmeep approved these changes

2022-04-20 16:16 UTC, merged